name: NeonTracker
options:
  bundleIdPrefix: com.neurosync
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

configs:
  Debug:
    xcconfig: Config/Secrets.xcconfig
  Release:
    xcconfig: Config/Secrets.xcconfig

targets:
  NeonTracker:
    type: application
    platform: iOS
    # Explicitly inherit configurations to ensure secrets are seen by the target
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    sources:
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.yml"
          - "*.md"
          - "*.sh"
          - ".DS_Store"
          - ".git"
          - "Logs"
          - ".gemini"
          - ".agent"
          - "Tests"
    resources:
      - path: Assets.xcassets
      - path: Resources
    info:
      path: Info.plist
      properties:
        OPENROUTER_API_KEY: $(OPENROUTER_API_KEY)
        UILaunchScreen: {}
        UIAppFonts:
          - Anta-Regular.ttf
          - Asimovian-Regular.ttf
          - Audiowide-Regular.ttf
          - Electrolize-Regular.ttf
          - Geo-Italic.ttf
          - Geo-Regular.ttf
          - Handjet-Bold.ttf
          - Handjet-ExtraLight.ttf
          - Handjet-Light.ttf
          - Handjet-Medium.ttf
          - Handjet-Regular.ttf
          - Handjet-SemiBold.ttf
          - Handjet-Thin.ttf
          - Iceberg-Regular.ttf
          - Iceland-Regular.ttf
          - KellySlab-Regular.ttf
          - MajorMonoDisplay-Regular.ttf
          - Megrim-Regular.ttf
          - Offside-Regular.ttf
          - Orbitron-Bold.ttf
          - Orbitron-Medium.ttf
          - Orbitron-Regular.ttf
          - Quantico-Bold.ttf
          - Quantico-BoldItalic.ttf
          - Quantico-Italic.ttf
          - Quantico-Regular.ttf
          - Rajdhani-Bold.ttf
          - Rajdhani-Medium.ttf
          - Rajdhani-Regular.ttf
          - Rajdhani-SemiBold.ttf
          - Rationale-Regular.ttf
          - ShareTechMono-Regular.ttf
          - Silkscreen-Bold.ttf
          - Silkscreen-Regular.ttf
          - SyneMono-Regular.ttf
          - TurretRoad-Bold.ttf
          - TurretRoad-ExtraBold.ttf
          - TurretRoad-ExtraLight.ttf
          - TurretRoad-Light.ttf
          - TurretRoad-Medium.ttf
          - TurretRoad-Regular.ttf
          - UbuntuMono-Bold.ttf
          - UbuntuMono-BoldItalic.ttf
          - UbuntuMono-Italic.ttf
          - UbuntuMono-Regular.ttf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neurosync.tracker
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.0"
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_PREVIEWS: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_STRICT_CONCURRENCY: complete

  NeonTests:
    type: bundle.unit-test
    platform: iOS
    configFiles:
      Debug: Config/Secrets.xcconfig
      Release: Config/Secrets.xcconfig
    sources:
      - path: Tests
    dependencies:
      - target: NeonTracker
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neurosync.tracker.tests
        SWIFT_VERSION: "6.0"
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_STRICT_CONCURRENCY: complete

schemes:
  NeonTracker:
    build:
      targets:
        NeonTracker: all
        NeonTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - NeonTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
